apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-production
  namespace: production
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-pv-production"
