apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-quality
  namespace: quality
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv-quality
  storageClassName: standard
